version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
    env_file: .env

    restart: always
    command: npm run start
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    env_file: .env

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  redis_data:
  postgres_data:
